### ISSUE TITLE
Module disconnection

### ISSUE THREAD

**Issue by Lelberto** [la-guirlande/guirlande-hub-backend#13]
Refactoring in modules service `unload()` by calling `disconnectAll()` instead of duplicate the code.

**Comment by Faichyer** [comment]
Carré dans le pentagone

**Comment by Faichyer** [comment]
Comme t'as bien fermé cette pute d'issue mon gourmand

**Comment by Lelberto** [comment]
> Comme t'as bien fermé cette pute d'issue mon gourmand

T'as vu cette rapidité
